[theme]
primaryColor = "#DD0426"
backgroundColor = "#EFF6EE"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#273043"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
