[theme]
base = "dark"
primaryColor = "#DD0426"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B24"
textColor = "#EFF6EE"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25
